package com.neohear.reminder

import android.app.NotificationManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.util.Log
import androidx.core.app.NotificationCompat
import com.neohear.MainActivity
import com.neohear.NeoHearApp
import com.neohear.data.AppDatabase
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Checks for referrals that are still PENDING after [pendingThresholdDays] days
 * and fires a simulated SMS log + Android system notification for each.
 *
 * Designed to be called from a background WorkManager job or on app launch.
 * For the hackathon build, we call it on app launch for simplicity.
 */
class FollowUpReminder(
    private val context: Context,
    private val database: AppDatabase,
    private val pendingThresholdDays: Long = DEFAULT_THRESHOLD_DAYS,
    private val now: Long = System.currentTimeMillis()
) {

    /**
     * Check all referrals and fire reminders for PENDING ones older than threshold.
     * Returns the list of reminder events that were generated.
     */
    suspend fun checkAndNotify(): List<ReminderEvent> {
        val cutoffTimestamp = now - (pendingThresholdDays * MS_PER_DAY)
        val overdueReferrals = database.referralDao().getPendingReferralsOlderThan(cutoffTimestamp)

        val events = mutableListOf<ReminderEvent>()
        for (referral in overdueReferrals) {
            val patient = database.patientDao().getById(referral.patientId)
            val event = ReminderEvent(
                referralId = referral.id,
                patientName = patient?.displayNameOrCode ?: "Unknown",
                patientId = referral.patientId.toString(),
                createdAt = referral.createdAt,
                daysPending = ((now - referral.createdAt) / MS_PER_DAY).toInt()
            )

            // Simulated SMS log
            val smsMessage = buildSmsMessage(event)
            SimulatedSmsLog.log(smsMessage)
            Log.w(TAG, smsMessage)

            // Fire Android notification
            fireNotification(event)

            events.add(event)
        }
        return events
    }

    private fun buildSmsMessage(event: ReminderEvent): String {
        val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.US)
        return buildString {
            append("[SIMULATED SMS] To: parent/guardian of ${event.patientName}\n")
            append("  Re: NeoHear hearing screening referral (created ${dateFormat.format(Date(event.createdAt))})\n")
            append("  Status: PENDING for ${event.daysPending} days\n")
            append("  Message: Your child's referral for follow-up hearing evaluation is still pending. ")
            append("Please contact the clinic to schedule an appointment.\n")
            append("  --- END SIMULATED SMS ---")
        }
    }

    private fun fireNotification(event: ReminderEvent) {
        val intent = Intent(context, MainActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TOP
            putExtra("navigate_to", "referral_detail")
            putExtra("referral_id", event.referralId.toString())
        }
        val pendingIntent = PendingIntent.getActivity(
            context,
            event.referralId.hashCode(),
            intent,
            PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
        )

        val notification = NotificationCompat.Builder(context, NeoHearApp.CHANNEL_REFERRAL_REMINDER)
            .setSmallIcon(android.R.drawable.ic_dialog_alert)
            .setContentTitle("Referral Follow-up Needed")
            .setContentText("${event.patientName} — pending ${event.daysPending} days")
            .setStyle(
                NotificationCompat.BigTextStyle()
                    .bigText(
                        "Referral for ${event.patientName} has been PENDING for ${event.daysPending} days. " +
                        "Please follow up with the family to schedule the hearing evaluation."
                    )
            )
            .setPriority(NotificationCompat.PRIORITY_DEFAULT)
            .setContentIntent(pendingIntent)
            .setAutoCancel(true)
            .build()

        val manager = context.getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        manager.notify(event.referralId.hashCode(), notification)
    }

    companion object {
        const val DEFAULT_THRESHOLD_DAYS = 14L
        const val MS_PER_DAY = 24L * 60 * 60 * 1000
        private const val TAG = "FollowUpReminder"
    }
}

/**
 * Represents a single reminder event generated by [FollowUpReminder].
 */
data class ReminderEvent(
    val referralId: java.util.UUID,
    val patientName: String,
    val patientId: String,
    val createdAt: Long,
    val daysPending: Int
)
